/*
 * 
 */
package com.main;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * @author Luke Mawby
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        topLeftTextField = new javax.swing.JTextField();
        topMiddleTextField = new javax.swing.JTextField();
        topRightTextField = new javax.swing.JTextField();
        middleLeftTextField = new javax.swing.JTextField();
        middleTextField = new javax.swing.JTextField();
        middleRightTextField = new javax.swing.JTextField();
        bottomLeftTextField = new javax.swing.JTextField();
        bottomMiddleTextField = new javax.swing.JTextField();
        bottomRightTextField = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        jLayeredPane10 = new javax.swing.JLayeredPane();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameBoard"); // NOI18N
        setResizable(false);

        topLeftTextField.setEditable(false);
        topLeftTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        topLeftTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topLeftTextField.setText("-");
        topLeftTextField.setFocusable(false);
        topLeftTextField.setRequestFocusEnabled(false);
        topLeftTextField.setVerifyInputWhenFocusTarget(false);
        topLeftTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topLeftTextFieldMouseClicked(evt);
            }
        });

        topMiddleTextField.setEditable(false);
        topMiddleTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        topMiddleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topMiddleTextField.setText("-");
        topMiddleTextField.setFocusable(false);
        topMiddleTextField.setRequestFocusEnabled(false);
        topMiddleTextField.setVerifyInputWhenFocusTarget(false);
        topMiddleTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topMiddleTextFieldMouseClicked(evt);
            }
        });

        topRightTextField.setEditable(false);
        topRightTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        topRightTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        topRightTextField.setText("-");
        topRightTextField.setFocusable(false);
        topRightTextField.setRequestFocusEnabled(false);
        topRightTextField.setVerifyInputWhenFocusTarget(false);
        topRightTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topRightTextFieldMouseClicked(evt);
            }
        });

        middleLeftTextField.setEditable(false);
        middleLeftTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        middleLeftTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        middleLeftTextField.setText("-");
        middleLeftTextField.setFocusable(false);
        middleLeftTextField.setRequestFocusEnabled(false);
        middleLeftTextField.setVerifyInputWhenFocusTarget(false);
        middleLeftTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleLeftTextFieldMouseClicked(evt);
            }
        });

        middleTextField.setEditable(false);
        middleTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        middleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        middleTextField.setText("-");
        middleTextField.setFocusable(false);
        middleTextField.setRequestFocusEnabled(false);
        middleTextField.setVerifyInputWhenFocusTarget(false);
        middleTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleTextFieldMouseClicked(evt);
            }
        });

        middleRightTextField.setEditable(false);
        middleRightTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        middleRightTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        middleRightTextField.setText("-");
        middleRightTextField.setFocusable(false);
        middleRightTextField.setRequestFocusEnabled(false);
        middleRightTextField.setVerifyInputWhenFocusTarget(false);
        middleRightTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleRightTextFieldMouseClicked(evt);
            }
        });

        bottomLeftTextField.setEditable(false);
        bottomLeftTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bottomLeftTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bottomLeftTextField.setText("-");
        bottomLeftTextField.setFocusable(false);
        bottomLeftTextField.setRequestFocusEnabled(false);
        bottomLeftTextField.setVerifyInputWhenFocusTarget(false);
        bottomLeftTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottomLeftTextFieldMouseClicked(evt);
            }
        });

        bottomMiddleTextField.setEditable(false);
        bottomMiddleTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bottomMiddleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bottomMiddleTextField.setText("-");
        bottomMiddleTextField.setFocusable(false);
        bottomMiddleTextField.setRequestFocusEnabled(false);
        bottomMiddleTextField.setVerifyInputWhenFocusTarget(false);
        bottomMiddleTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottomMiddleTextFieldMouseClicked(evt);
            }
        });

        bottomRightTextField.setEditable(false);
        bottomRightTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bottomRightTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bottomRightTextField.setText("-");
        bottomRightTextField.setFocusable(false);
        bottomRightTextField.setRequestFocusEnabled(false);
        bottomRightTextField.setVerifyInputWhenFocusTarget(false);
        bottomRightTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottomRightTextFieldMouseClicked(evt);
            }
        });

        jLayeredPane3.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane3.setEnabled(false);
        jLayeredPane3.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLayeredPane4.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane4.setEnabled(false);
        jLayeredPane4.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLayeredPane5.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane5.setEnabled(false);
        jLayeredPane5.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jLayeredPane6.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane6.setEnabled(false);
        jLayeredPane6.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jLayeredPane7.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane7.setEnabled(false);
        jLayeredPane7.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jLayeredPane8.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane8.setEnabled(false);
        jLayeredPane8.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jLayeredPane9.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane9.setEnabled(false);
        jLayeredPane9.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jLayeredPane10.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane10.setEnabled(false);
        jLayeredPane10.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane10Layout = new javax.swing.GroupLayout(jLayeredPane10);
        jLayeredPane10.setLayout(jLayeredPane10Layout);
        jLayeredPane10Layout.setHorizontalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane10Layout.setVerticalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(middleLeftTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottomLeftTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(bottomMiddleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bottomRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane7)
                            .addComponent(jLayeredPane10))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(middleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topMiddleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(middleRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane4)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(topMiddleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(topLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(topRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(middleLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(middleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(middleRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bottomRightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bottomMiddleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bottomLeftTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topLeftTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topLeftTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_topLeftTextFieldMouseClicked

    private void topMiddleTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMiddleTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_topMiddleTextFieldMouseClicked

    private void middleRightTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleRightTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_middleRightTextFieldMouseClicked

    private void middleLeftTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleLeftTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_middleLeftTextFieldMouseClicked

    private void middleTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_middleTextFieldMouseClicked

    private void topRightTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topRightTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_topRightTextFieldMouseClicked

    private void bottomLeftTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomLeftTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_bottomLeftTextFieldMouseClicked

    private void bottomMiddleTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomMiddleTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_bottomMiddleTextFieldMouseClicked

    private void bottomRightTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottomRightTextFieldMouseClicked
        textBoxClicked(evt);
    }//GEN-LAST:event_bottomRightTextFieldMouseClicked

    public void textBoxClicked(java.awt.event.MouseEvent evt) {
        int aiPositionChosen;
        GameAIPlayer gameAIPlayer = new GameAIPlayer();

        javax.swing.JTextField textField = (javax.swing.JTextField) evt.getSource();

        //Test if the clicked box is empty
        if (textField.getText().equals("O") || textField.getText().equals("X")) {
            JOptionPane.showMessageDialog(null, "The selected box is occupied", "Occupied!",
                    JOptionPane.OK_OPTION);
        } else {
            textField.setText("X");
            testConditions();
        }

        aiPositionChosen = gameAIPlayer.choosePosition(getBoardPositions());
        setBoardPosition(aiPositionChosen);
        testConditions();
    }

    public void testConditions() {
        boolean[] conditions;
        boolean playerWin;
        boolean playerLose;
        boolean playerDraw;
        GameStatus gameStatus = new GameStatus();

        conditions = gameStatus.checkConditions(getBoardPositions());
        playerWin = conditions[0];
        playerLose = conditions[1];
        playerDraw = conditions[2];

        if (playerWin || playerLose || playerDraw) {
            if (playerWin) {
                gameOverOptions("You Win, Play Again?", "");
            } else if (playerLose) {
                gameOverOptions("You Lose, Play Again?", "");
            } else if (playerDraw) {
                gameOverOptions("Draw, Play Again?", "");
            }
        }
    }

    public void gameOverOptions(String message, String title) {
        int dialogResult = 0;

        dialogResult = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            resetGame();
            //Save result
        } else {
            System.exit(0);
        }
    }

    public void resetGame() {

        topLeftTextField.setText("-");
        topMiddleTextField.setText("-");
        topRightTextField.setText("-");
        middleLeftTextField.setText("-");
        middleTextField.setText("-");
        middleRightTextField.setText("-");
        bottomLeftTextField.setText("-");
        bottomMiddleTextField.setText("-");
        bottomRightTextField.setText("-");
    }

    public String[] getBoardPositions() {

        String[] currentBoard = new String[9];
        currentBoard[0] = topLeftTextField.getText();
        currentBoard[1] = topMiddleTextField.getText();
        currentBoard[2] = topRightTextField.getText();
        currentBoard[3] = middleLeftTextField.getText();
        currentBoard[4] = middleTextField.getText();
        currentBoard[5] = middleRightTextField.getText();
        currentBoard[6] = bottomLeftTextField.getText();
        currentBoard[7] = bottomMiddleTextField.getText();
        currentBoard[8] = bottomRightTextField.getText();

        return currentBoard;
    }

    public void setBoardPosition(int position) {

        JTextField[] currentBoard = new JTextField[9];

        currentBoard[0] = topLeftTextField;
        currentBoard[1] = topMiddleTextField;
        currentBoard[2] = topRightTextField;
        currentBoard[3] = middleLeftTextField;
        currentBoard[4] = middleTextField;
        currentBoard[5] = middleRightTextField;
        currentBoard[6] = bottomLeftTextField;
        currentBoard[7] = bottomMiddleTextField;
        currentBoard[8] = bottomRightTextField;

        currentBoard[position].setText("O");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bottomLeftTextField;
    private javax.swing.JTextField bottomMiddleTextField;
    private javax.swing.JTextField bottomRightTextField;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField middleLeftTextField;
    private javax.swing.JTextField middleRightTextField;
    private javax.swing.JTextField middleTextField;
    private javax.swing.JTextField topLeftTextField;
    private javax.swing.JTextField topMiddleTextField;
    private javax.swing.JTextField topRightTextField;
    // End of variables declaration//GEN-END:variables
}
